/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QQuoteRowRouteImport } from './routes/q.$quoteRow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QQuoteRowRoute = QQuoteRowRouteImport.update({
  id: '/q/$quoteRow',
  path: '/q/$quoteRow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/q/$quoteRow': typeof QQuoteRowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/q/$quoteRow': typeof QQuoteRowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/q/$quoteRow': typeof QQuoteRowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/q/$quoteRow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/q/$quoteRow'
  id: '__root__' | '/' | '/q/$quoteRow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QQuoteRowRoute: typeof QQuoteRowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$quoteRow': {
      id: '/q/$quoteRow'
      path: '/q/$quoteRow'
      fullPath: '/q/$quoteRow'
      preLoaderRoute: typeof QQuoteRowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QQuoteRowRoute: QQuoteRowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
